// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'root_screen_view_models.dart';

// These functions are ignored because they are not marked as `pub`: `initial`

class RootScreenState {
  final String name;

  const RootScreenState({
    required this.name,
  });

  Future<RootScreenViewModel> render() => RustLib.instance.api
          .crateApiScreensRootScreenRootScreenStateRootScreenStateRender(
        that: this,
      );

  @override
  int get hashCode => name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RootScreenState &&
          runtimeType == other.runtimeType &&
          name == other.name;
}
