[package]
name = "rust_lib_generics_frb"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.1.0"
if_chain = "1.0.2"
tokio = {version = "1.38.1", features = ["full"] }